// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2yOlrIUKJYy22D6GvtB9yjocne06LDZg',
    appId: '1:370281908169:web:1cceea49a49a284808ca18',
    messagingSenderId: '370281908169',
    projectId: 'task-management-app-d2268',
    authDomain: 'task-management-app-d2268.firebaseapp.com',
    storageBucket: 'task-management-app-d2268.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw9h1nXcYVBt7olW5rGHEWA9mAVWmsv4c',
    appId: '1:370281908169:android:d6ccf38535dd8cc508ca18',
    messagingSenderId: '370281908169',
    projectId: 'task-management-app-d2268',
    storageBucket: 'task-management-app-d2268.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHVRs9WUghMfbeRU6UTwxGcPswHwWFWug',
    appId: '1:370281908169:ios:69dbaba596d5a3a608ca18',
    messagingSenderId: '370281908169',
    projectId: 'task-management-app-d2268',
    storageBucket: 'task-management-app-d2268.appspot.com',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHVRs9WUghMfbeRU6UTwxGcPswHwWFWug',
    appId: '1:370281908169:ios:69dbaba596d5a3a608ca18',
    messagingSenderId: '370281908169',
    projectId: 'task-management-app-d2268',
    storageBucket: 'task-management-app-d2268.appspot.com',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2yOlrIUKJYy22D6GvtB9yjocne06LDZg',
    appId: '1:370281908169:web:30a0da3867d9fa2608ca18',
    messagingSenderId: '370281908169',
    projectId: 'task-management-app-d2268',
    authDomain: 'task-management-app-d2268.firebaseapp.com',
    storageBucket: 'task-management-app-d2268.appspot.com',
  );
}
